name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
         sudo apt update
         sudo apt install -y tesseract-ocr libtesseract-dev libleptonica-dev
        if: runner.os == 'Linux' 
      - run: pip install uv
      - run: uv sync
      - name: Find Tesseract data path
        run: |
          TESSDATA_PATH=$(dpkg -L tesseract-ocr-eng | grep -E 'tessdata$' | head -1)
          echo "TESSDATA_PATH=$TESSDATA_PATH" >> $GITHUB_ENV
      - name: tests
        env: 
          TESS_DATA_PATH: /usr/share/tesseract-ocr/4.00/tessdata
        run: uv run python -m pytest tests/ -v --cov=src/
      - run: uv ruff check