name: CI
on:
  - push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: choco install tesseract -y
      - run: echo "TESS_DATA_PATH=C:\Program Files\Tesseract-OCR\tessdata" >> $env:GITHUB_ENV
      - run: pip install uv
      - run: uv sync
      - name: tests
        env: 
          TESS_DATA_PATH: C:\Program Files\Tesseract-OCR\tessdata
        run: uv run python -m pytest tests/ -v --cov=src/
      - run: uv run ruff check