name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
         sudo apt update
         sudo apt install -y tesseract-ocr-eng libtesseract-dev libleptonica-dev
        if: runner.os == 'Linux' 
      - name: Set TESS_DATA_PATH
        run: |
          TESSDATA_PATH=$(find /usr/share/tesseract-ocr -name tessdata -type d | head -1)
          echo "TESS_DATA_PATH=$TESSDATA_PATH" >> $GITHUB_ENV
      - run: pip install uv
      - run: uv sync
      - name: tests
        env: 
          TESS_DATA_PATH: /usr/share/tesseract-ocr/4.00/tessdata
        run: uv run python -m pytest tests/ -v --cov=src/
      - run: uv ruff check